### ISSUE TITLE
WP Plugin (Lido) Alternative

### ISSUE THREAD

**Issue by catenacap** [lidofinance/ethereum-validators-monitoring#181]
Already one active for Lido on Wordpress.

https://github.com/catenacap/Lido-stETH-Rewards-Plugin-wordpress-

**Comment by dgusakov** [comment]
@catenacap Thank you for sharing the resource. Can you elaborate on how the resource provided is related to the [ethereum-validators-monitoring](https://github.com/lidofinance/ethereum-validators-monitoring), and what is your proposal or issue?
